version: "3.3"

services:
  frontend:
    container_name: tacs-frontend
    build: ./frontend
    ports:
      - 3000:3000
    environment: 
      - NEXT_PUBLIC_API_URL=http://localhost:8080
  backend:
    container_name: tacs-backend
    build: .
    ports:
      - 8080:8080
    environment:
      SUPERHERO_API_KEY: "${SUPERHERO_API_KEY}"
